image: docker:latest
services:
  - docker:dind
stages:
  - build
  - deploy

build:
  before_script:
    - docker info
  stage: build
  script:
    - docker login -u $CI_BUILD_USER -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/fronbasal/gimmecock-frontend .
    - docker push registry.gitlab.com/fronbasal/gimmecock-frontend
  only:
    - master

